# Generated by Django 3.0.3 on 2020-02-06 13:02

from django.db import migrations, models
import tst.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10, validators=[tst.models.validate_roll])),
                ('name', models.CharField(max_length=50)),
                ('passkey', models.CharField(max_length=6, validators=[tst.models.validate_key])),
                ('resp', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('roll_no', 'passkey')},
            },
        ),
    ]
