# Generated by Django 3.0.3 on 2020-02-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resp',
            old_name='roll_no',
            new_name='user',
        ),
    ]
